[[redirects]]
force = true
from = '/api/*'
status = 200
to = '/.netlify/functions/:splat'

# The following redirect is intended for use with most SPAs that handle
# routing internally.
[[redirects]]
from = '/*'
status = 200
to = '/index.html'

#[[headers]]
#  # Define which paths this specific [[headers]] block will cover.
#  for = "/*"
#    [headers.values]
#    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"

[dev]
functionsPort = 8885

[functions]
  external_node_modules = ["mongodb"]
  node_bundler = "esbuild"

